services:
  - type: web
    name: hedgedoc
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /status
    plan: free
    envVars:
      - key: PORT
        value: 3000
    disk:
      name: hedgedoc-data
      mountPath: /hedgedoc/data
      sizeGB: 1
